# Generated by Django 6.1 on 2026-08-26 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(help_text="Contact person's name.", max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('business_location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'vendor categories',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('products_services', models.TextField(blank=True)),
                ('requirement', models.CharField(blank=True, choices=[('Exhibition Space', 'Exhibition Space'), ('Vendor Stall', 'Vendor Stall'), ('Food & Beverage Stall', 'Food & Beverage Stall'), ('Corporate Activation', 'Corporate Activation'), ('Branding / Promotional Space', 'Branding / Promotional Space'), ('Other', 'Other')], max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='vendors.vendorcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
