# Generated by Django 6.1 on 2026-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
