# Generated by Django 6.1 on 2026-08-20 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=30)),
                ('payment_method', models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ZAMTEL_KWACHA', 'Zamtel Kwacha'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], max_length=30)),
                ('billing_details', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
