# Generated by Django 6.1 on 2026-08-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('registrations', '0002_alter_registration_registration_number'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors.vendorregistration'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.registration'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('registration__isnull', False), ('vendor_registration__isnull', True)), models.Q(('registration__isnull', True), ('vendor_registration__isnull', False)), _connector='OR'), name='payment_exactly_one_target'),
        ),
    ]
